packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@types/node": ^24
  jsdom: ^29.0.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-solid: ^2.11.12
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
